install strimzi operator in kubectl_dependencies job

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -23,6 +23,14 @@ setup_kubectl_dependencies:
       else
         export K8S_CONTEXT=$PROD_CONTEXT
       fi
+    - |
+        if ! kubectl get deployment strimzi-cluster-operator -n default &> /dev/null; then
+          echo "Strimzi operator not found. Installing..."
+          kubectl apply -f ./message-broker/k8s/strimzi-cluster-operator-0.31.1.yaml
+          kubectl wait --for=condition=available --timeout=300s deployment/strimzi-cluster-operator -n default
+        else
+          echo "strimzi oeprator already exists"
+        fi
     
     - kubectl config use-context $K8S_CONTEXT
     - echo "After setting context:"
